server:
  port: 80

app:
  logging-to: console # option are: console / file
  drone:
    video-ws-endpoint: /videofeed
    video-server-port: 1313
   ###  importent - determine the number of drones that can connect (1 byte - 2^8 - 1 = 255 drones).
   ##     its set to parse the x bytes of the recieved data package for the drone id. 
    drone-id-length: 1 

  logging:
    level:
      org.springframework: INFO
      com.droneshield.cloudapp: DEBUG
